"use client";

import './globals.css'
import { Inter } from 'next/font/google'
import { ChakraProvider, Flex, Box, Heading, Text } from '@chakra-ui/react';
import TopNav from '@/components/layout/TopNav';
import SideNav from '@/components/layout/SideNav';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={[inter.className, 'w-full h-[auto]']}>
        <ChakraProvider>
          <Flex bgColor={'#749D1C'} p={3} gap={'1em'} w={'full'} style={{ height: '100%', borderRadius: '3em' }}>
            <SideNav styles={{ margin: '1em' }} />
            <Box w={'full'} bgColor={'#F7F7F7'} p={'1em'} px={'2em'} style={{ borderRadius: '3em' }}>
              <TopNav />
              <Heading>Welcome <Text as={'bold'} color={'#749D1C'}>Dr. Amzat!</Text></Heading>
              <main className='w-full pt-3'>
                {children}
              </main>
            </Box>
          </Flex>
        </ChakraProvider>
      </body>
    </html>
  )
}
